apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: aroti
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/aroti
  KC_DB_USERNAME: postgres
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
