apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aroti

resources:
- namespace.yaml
- database/postgres-pvc.yaml
- database/postgres-configmap.yaml
- database/postgres-secret.yaml
- database/postgres-deployment.yaml
- redis/redis-deployment.yaml
- keycloak/keycloak-configmap.yaml
- keycloak/keycloak-secret.yaml
- keycloak/keycloak-deployment.yaml
- backend/backend-configmap.yaml
- backend/backend-deployment.yaml
- backend/backend-worker-deployment.yaml
- ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: aroti
  app.kubernetes.io/managed-by: kustomize
